# config/agent_config.yaml

# DQN Agent Configuration
gamma: 0.99
learning_rate: 0.0005
epsilon_start: 1.0
epsilon_min: 0.01
epsilon_decay: 0.995
batch_size: 32
memory_size: 100000
hidden_size: 256
target_update_frequency: 10
lr_decay: 0.995
min_lr: 0.00001
use_shared_memory: true