# config/agent_config.yaml

# DQN Agent Configuration
gamma: 0.95
learning_rate: 0.001
epsilon_start: 1.0
epsilon_min: 0.01
epsilon_decay: 0.995
batch_size: 32
memory_size: 10000
hidden_size: 64
target_update_frequency: 100