# config/casf_config.yaml

model_name: CASF
version: 1.2

files:
  net_file: "baseline/osm.net.xml.gz"
  route_file: "baseline/osm.passenger.trips.xml"

training:
  num_episodes: 20         # Number of training episodes
  steps_per_episode: 600     # Number of steps per episode
  batch_size: 128
  gamma: 0.95
  tau: 0.01
  update_every: 1

model:
  state_encoder_units: [256, 128]
  state_embedding_dim: 64
  num_attention_heads: 4
  key_dim: 32
  value_dim: 32
  dropout: 0.1
  max_neighbors: 4
  communication_range: 300
  distance_embedding_dim: 16
  fusion_hidden_units: [128, 64]
  final_state_dim: 32
  actor_hidden_units: [64, 32]
  critic_hidden_units: [64, 32]
  learning_rate: 0.001       # Moved from training to model
  grad_clip: 0.5             # Moved from training to model

environment:
  observation_dim: 28  # Fixed size for all states
  action_dim: 1        # Changed from 4 to 1
  max_episode_steps: 200  # Changed from 1000 to 200 to align with steps_per_episode
  max_neighbors: 4
  communication_range: 1000
  max_phase_duration: 60
  reward_weights:        # Moved under environment
    waiting_time: 1.0
    queue_length: 1.0
    throughput: 1.0

memory:
  capacity: 200000          # Increased from 100000 to 200000
  prioritized_replay: true
  alpha: 0.6
  beta: 0.4
  epsilon: 0.01

logging:
  log_interval: 100
  checkpoint_interval: 1       # Changed from 5 to 1 to save checkpoints every episode
  eval_interval: 500