# config/hierarchical_config.yaml

# Base Simulation Configuration (matching baseline)
simulation:
  net_file: "baseline/osm.net.xml.gz"
  trip_file: "baseline/osm.passenger.trips.xml"
  num_episodes: 10
  max_steps: 50
  use_gui: false
  step_length: 0.5  # Reduced for finer control
  delta_time: 2  # Reduced for more frequent updates
  time_to_teleport: 100  # Further reduced to prevent gridlocks

# Hierarchical Structure Configuration
hierarchy:
  num_regions: 12  # Increased for more granular control
  intersections_per_region: 2  # Further reduced for more manageable regions
  coordinator_update_freq: 2  # More frequent coordination
  local_update_freq: 1  # More frequent local updates

# Agent Configuration
agent:
  state_size: 48  # Further increased state space
  coordinator_state_size: 96  # Increased for better coordination
  action_size: 4
  hidden_sizes: [512, 384, 256, 128]  # Even deeper network
  
  # Training Parameters
  gamma: 0.98  # Slightly increased to consider longer-term rewards
  learning_rate: 0.0005  # Reduced to stabilize learning
  epsilon_start: 1.0
  epsilon_min: 0.01  # Further reduced
  epsilon_decay: 0.9975  # Slower decay for more exploration
  target_update_freq: 20  # More frequent updates
  
  # Memory Parameters
  batch_size: 512  # Even larger batches
  memory_size: 1000000  # Massive memory for more experience

# Training Configuration
training:
  eval_frequency: 3
  save_frequency: 5
  checkpoint_dir: "checkpoints/hierarchical_extended"
  log_dir: "logs/hierarchical_extended"
  
  # Reward Configuration - More nuanced weighting
  reward_weights:
    waiting_time: -0.95  # Even higher weight on waiting time
    queue_length: -0.05  # Minimal queue length penalty
    throughput: 0.01  # Minimal throughput reward
    
  # Coordination weights for different reward components
  coordination_weights:
    local: 0.7  # Increased local control
    regional: 0.25  # Adjusted regional
    global: 0.05  # Reduced global

# Evaluation Configuration
evaluation:
  num_episodes: 10  # Matching baseline num_episodes
  metrics:
    - average_waiting_time
    - average_queue_length
    - total_throughput
    - coordination_score

# Metrics Configuration (matching baseline)
metrics:
  episode: []
  step: []
  total_waiting_time: []
  total_throughput: []
  average_speed: []
  vehicles_in_network: []
  completed_trips: []