# config/independent_agents.yaml

environment:
  use_gui: false
  num_seconds: 3600
  delta_time: 5
  yellow_time: 2
  min_green: 5
  max_green: 50
  max_depart_delay: 100000
  time_to_teleport: -1
  
agent:
  # Learning parameters
  gamma: 0.95
  learning_rate: 0.001
  batch_size: 32
  memory_size: 100000
  target_update: 10
  tau: 0.001  # For soft updates
  
  # Network architecture
  hidden_size: 64
  
  # Exploration parameters
  epsilon_start: 1.0
  epsilon_min: 0.01
  epsilon_decay: 0.995