# config/maddpg_config.yaml

# Network and Route file paths (matching baseline)
sumo_network:
  net_file: "baseline/osm.net.xml.gz"
  route_file: "baseline/osm.passenger.trips.xml"

# Training parameters
training:
  num_episodes: 1  # Reduced number of episodes for quicker training
  max_steps_per_episode: 50  # Reduced to 100 steps as requested
  batch_size: 64
  learning_rate_actor: 0.001
  learning_rate_critic: 0.001
  gamma: 0.95  # Discount factor
  tau: 0.01    # Soft update parameter
  update_every: 50
  warmup_steps: 10
  evaluate_every: 1  # Evaluate more frequently due to fewer episodes

# Memory settings
memory:
  capacity: 200000
  min_size_for_training: 128
  alpha: 0.7

# Neural Network Architecture
network:
  actor:
    hidden_layers: [256, 128]
    activation: "relu"
    output_activation: "tanh"
  critic:
    hidden_layers: [256, 128]
    activation: "relu"
    output_activation: "linear"

# Environment settings (matched with baseline)
environment:
  use_gui: false
  num_seconds: 3600  # 1 hour simulation
  delta_time: 1      # 1 second timesteps, matching baseline
  yellow_time: 3     # Updated to match SUMO default/baseline
  min_green: 5       # Matches baseline
  max_green: 60      # Updated to match baseline
  time_to_teleport: 300  # Added to match baseline teleport setting
  num_agents: 112    # Will be automatically adjusted based on valid traffic lights
  reward_weights:    # Aligned with baseline reward calculation
    waiting_time: -0.4
    queue_length: -0.3
    speed: 0.3
  demand_scale: 1.0  # Matches baseline traffic load

# Noise parameters for exploration
noise:
  type: "OrnsteinUhlenbeck"
  mu: 0.0
  theta: 0.15
  sigma: 0.2
  decay: 0.9995

# Logging and checkpoint settings
logging:
  log_dir: "logs/maddpg"
  model_dir: "models/maddpg"
  save_frequency: 2  # Save every 2 episodes
  tensorboard: true
  log_level: "INFO"  # Changed from DEBUG to reduce log volume

# Device settings
device:
  use_gpu: false  # Set to true if using CUDA-capable GPU
  gpu_id: 0

# Evaluation settings
evaluation:
  eval_episodes: 2
  render: false  # Matches baseline (no GUI)
  save_eval_stats: true
  eval_seed: 42  # Fixed seed for reproducible evaluation

# SUMO-specific settings (matching baseline)
sumo:
  step_length: 1.0
  no_warnings: true
  begin: 0
  time_to_teleport: 300  # Matches baseline
  no_step_log: true